import { Interest } from "../types";

export const availableInterests: string[] = [
  "Technology",
  "Science",
  "Art",
  "Music",
  "Sports",
  "Cooking",
  "Travel",
  "Fashion",
  "Health",
  "Fitness",
  "Business",
  "Finance",
  "Education",
  "Politics",
  "History",
  "Philosophy",
  "Psychology",
  "Sociology",
  "Economics",
  "Marketing",
  "Management",
  "Leadership",
  "Entrepreneurship",
  "Innovation",
  "Design",
  "Engineering",
];

export const availableLanguages: any[] = [
  { id: "en", name: "English" },
  { id: "es", name: "Spanish" },
  { id: "fr", name: "French" },
  { id: "de", name: "German" },
  { id: "it", name: "Italian" },
  { id: "jp", name: "Japanese" },
  { id: "kr", name: "Korean" },
  { id: "ch", name: "Chinese" },
  { id: "ru", name: "Russian" },
  { id: "ar", name: "Arabic" },
  { id: "pt", name: "Portuguese" },
  { id: "nl", name: "Dutch" },
  { id: "pl", name: "Polish" },
  { id: "tr", name: "Turkish" },
  { id: "th", name: "Thai" },
  { id: "vi", name: "Vietnamese" },
  { id: "id", name: "Indonesian" },
  { id: "hi", name: "Hindi" },
  { id: "bn", name: "Bengali" },
  { id: "ms", name: "Malay" },
  { id: "tl", name: "Tagalog" },
  { id: "sw", name: "Swahili" },
  { id: "am", name: "Amharic" },
  { id: "fa", name: "Persian" },
  { id: "he", name: "Hebrew" },
  { id: "ur", name: "Urdu" },
  { id: "ne", name: "Nepali" },
  { id: "pa", name: "Punjabi" },
  { id: "gu", name: "Gujarati" },
  { id: "ta", name: "Tamil" },
  { id: "te", name: "Telugu" },
  { id: "ml", name: "Malayalam" },
  { id: "si", name: "Sinhala" },
  { id: "my", name: "Burmese" },
];

export const proficiencyLevels = ["A1", "A2", "B1", "B2", "C1", "C2"];
